apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sentinel-prod

resources:
  - ../../base

images:
  - name: sentinel/api-service
    newName: sentinel/api-service
    newTag: prod-initial
  - name: sentinel/worker-service
    newName: sentinel/worker-service
    newTag: prod-initial

