apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sentinel-stage

resources:
  - ../../base

images:
  - name: sentinel/api-service
    newName: ghcr.io/stevebanin/sentinel-api-service
    newTag: sha-bootstrap
  - name: sentinel/worker-service
    newName: ghcr.io/stevebanin/sentinel-worker-service
    newTag: sha-bootstrap

